// Code generated by cmd/cgo; DO NOT EDIT.

//line govosk.go:1:1
package govosk

// #include "vosk_api.h"
import _ "unsafe"

// NewModel creates a new VoskModel instance
func NewModel(modelPath) (*VoskModel, error) {
	var internal * /*line :8:16*/_Ctype_struct_VoskModel /*line :8:34*/
	internal = ( /*line :9:13*/_Cfunc_vosk_model_new /*line :9:28*/)(modelPath)
	model := &VoskModel{model: internal}
	return model, nil
}

// NewRecognizer creates a new VoskRecognizer instance
func NewRecognizer(model *VoskModel) (*VoskRecognizer, error) {
	var internal * /*line :16:16*/_Ctype_struct_VoskRecognizer /*line :16:39*/
	internal = func() *_Ctype_struct_VoskRecognizer{ _cgo0 := /*line :17:35*/model.model; var _cgo1 _Ctype_float = /*line :17:48*/16000.0; _cgoCheckPointer(_cgo0, nil); return _Cfunc_vosk_recognizer_new(_cgo0, _cgo1); }()
	rec := &VoskRecognizer{rec: internal}
	return rec, nil
}

func freeModel(model *VoskModel) {
	func() { _cgo0 := /*line :23:20*/model.model; _cgoCheckPointer(_cgo0, nil); _Cfunc_vosk_model_free(_cgo0); }()
}

func freeRecognizer(recognizer *VoskRecognizer) {
	func() { _cgo0 := /*line :27:25*/recognizer.rec; _cgoCheckPointer(_cgo0, nil); _Cfunc_vosk_recognizer_free(_cgo0); }()
}

// NewSpkModel creates a new VoskSpkModel instance
func NewSpkModel() {
	// TODO
}

// VoskModel contains a reference to the C VoskModel
type VoskModel struct {
	model * /*line :37:9*/_Ctype_struct_VoskModel /*line :37:27*/
}

// VoskSpkModel contains a reference to the C VoskSpkModel
type VoskSpkModel struct {
	spkModel * /*line :42:12*/_Ctype_struct_VoskSpkModel /*line :42:33*/
}

// VoskRecognizer contains a reference to the  C VoskRecognizer
type VoskRecognizer struct {
	rec * /*line :47:7*/_Ctype_struct_VoskRecognizer /*line :47:30*/
}
